select * from MYDB.CASESTUDY2_EXTARCTEDDATA.CUSTOMER
inner join MYDB.CASESTUDY2_EXTARCTEDDATA.TRANSACTION_Data
on MYDB.CASESTUDY2_EXTARCTEDDATA.CUSTOMER.CUSTOMER_ID = MYDB.CASESTUDY2_EXTARCTEDDATA.TRANSACTION_Data.Customer_ID